name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      DOCKER_REPOSITORY:
        description: 'Provide the docker repository name'     
        required: true
        default: 'kallor/test'
      IMAGE_TAG:
        description: 'Provide the docker image tag'     
        required: true
        default: 'latest'

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./calculator
          push: true
          tags: ${{ github.event.inputs.DOCKER_REPOSITORY }}:${{ github.event.inputs.IMAGE_TAG }}
